### ISSUE TITLE
[lazyxds] lazyxds create wrong sidecar CRD for service which type is externalName 

### ISSUE THREAD

**Issue by stanxing** [aeraki-framework/aeraki#83]
**Describe the bug**
For Service with `externalName` type, currently lazy xds will handle it the same as cluster ip. But externalName service does not have `selector` field, so it will create `Sidecar`  CRD with empty workload selector. According to [istio docs](https://istio.io/latest/docs/reference/config/networking/sidecar/#Sidecar),  In the absence of a workloadSelector, it will apply to all workload instances in the same namespace. It is very dangerous.

**To Reproduce**
1. Create service with externalName type, such as:

```
apiVersion: v1
kind: Service
metadata:
  name: example
  namespace: default
spec:
  externalName: www.baidu.com
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  sessionAffinity: None
  type: ExternalName
```

2. Kubectl get sidecar lazyxds-example -o yaml

```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: lazyxds-example
  namespace: default
spec:
  egress:
  - hosts:
    - istio-system/*
    - ...
  workloadSelector: {}
```

**Expected behavior**

I do not have perfect solution, maybe it's not necessary to generate `Sidecar` CRD for externalName service?

Also, currently there is no way to disable lazy XDS for the specified service, if I annotate `azy-xds=true` for one namespace.
