### ISSUE TITLE
Use Dubbo's metadata to match routes

### ISSUE THREAD

**Issue by Marco-Zheng** [aeraki-framework/aeraki#95]
**Is your feature request related to a problem? Please describe.**
Per we used dubbo for rpc calls, and expect to build gray deploy, and we may use different indicators for gray routing, such as version/userId ... now we can only add a spring starter to resolve this problem per Istio does not support TCP calls friendly

**Describe the solution you'd like**
If there any method to route by dubbo metadata（such as provider's version is 1.0.0, the consumer is also 1.0.0, it can select the 1.0.0 provider）

**Comment by zhaohuabing** [comment]
Do you mean Dubbo attachment when you talk about metadata? Yes, we can route traffic based on it. An example:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: test-dubbo-route
  namespace: dubbo
spec:
  hosts:
  - org.apache.dubbo.samples.basic.api.demoservice
  http:
  - name: route-batchjob
    match:
    - headers:
        batchJob:
          exact: "true"
    route:
    - destination:
        host: org.apache.dubbo.samples.basic.api.demoservice
        subset: batchjob
  - name: route-user
    match:
    - headers:
        batchJob:
          exact: "false"
    route:
    - destination:
        host: org.apache.dubbo.samples.basic.api.demoservice
        subset: user
```

If you need more flexible routing policies, please take a look at [MetaProtocol](https://github.com/aeraki-framework/meta-protocol-proxy).  In theory, any attributes in the Dubbo package could be put into the metadata of  MetaProtocol, and they can be used for routing. MetProtocol also supports RDS, so no connection interruption when routes change, much better than the original Dubbo proxy.  I'm very interested in your Dubbo use case. Could you please send me an email or contact me vi weChat(zhao_huabing). I can see there's a good potential that we could cooperate on those use cases.
